[package]
name = "ssimulacra2_rs"
version = "0.3.0"
edition = "2021"
description = "Binary exposing the ssimulacra2 rust implementation"
repository = "https://github.com/rust-av/ssimulacra2_bin"
homepage = "https://github.com/rust-av/ssimulacra2_bin"
license = "BSD-2-Clause"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
av-metrics-decoders = { version = "0.1.9", features = [
    "ffmpeg",
], optional = true }
clap = { version = "4.0.18", features = ["derive"] }
ffmpeg-next = { version = "5.1.1", optional = true }
image = "0.24.4"
num-traits = { version = "0.2.15", optional = true }
plotters = { version = "0.3.4", default_features = false, features = [
    "histogram",
    "svg_backend",
], optional = true }
ssimulacra2 = "0.2.0"
statrs = { version = "0.16.0", optional = true }

[profile.release]
lto = "thin"
codegen-units = 1

[features]
default = ["ffmpeg"]
ffmpeg = [
    "av-metrics-decoders",
    "plotters",
    "statrs",
    "num-traits",
    "ffmpeg-next",
    "ffmpeg-next/non-exhaustive-enums",
]
ffmpeg_build = ["ffmpeg", "av-metrics-decoders/ffmpeg_build"]

[patch.crates-io]
ffmpeg-next = { git = "https://github.com/FreezyLemon/rust-ffmpeg", branch = "non-exhaustive-enum" }
ffmpeg-sys-next = { git = "https://github.com/FreezyLemon/rust-ffmpeg-sys", branch = "non-exhaustive-enum" }
